# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('home', '0003_auto_20160826_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='projectImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
